### ISSUE TITLE
Download MediaFiles and interviewer instruction

### ISSUE THREAD

**Issue by pbillava** [NIPOSoftware/Nfield-SDK#155]
Hi,

Am trying to download media files and interviewer instruction using api as below
GET v1/Surveys/{surveyId}/MediaFiles/{fileName}
However it does not return complete file bytes. Please help

**Comment by joukevandermaas** [comment]
Hi @pbillava,

Please send us an email with your question at helpdesk@nipo.com. We will be able to help you that way.

Thank you
